import "./globals.css";

import { CartProvider } from "./components/context/CartContext";
import Footer from "@/app/components/ui/Footer"
import Header from "./components/ui/Header";

export const metadata=  {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
     <html lang="en">
       <body>
        <CartProvider>
         <Header/>
         {children}
         <Footer/>
        </CartProvider>
       </body>
     </html>
   )
 }
 